// Re-export all hooks from the Firestore-backed implementation
export {
  useStudents,
  useTeachers,
  useClasses,
  useSubjects,
  useAttendance,
  useLessons,
  useAssignments,
  useAssignmentSubmissions,
  useExams,
  useExamResults,
  useFeePayments,
  useAnnouncements,
  useEnquiries,
  useEvents,
  useNotifications,
  useDashboardStats,
  useStudentPerformance,
  useClassStatistics,
  useFeeInvoices,
} from './useFirestoreData';

export type {
  Student,
  Teacher,
  Class,
  Subject,
  AttendanceRecord,
  LessonLog,
  Assignment,
  AssignmentSubmission,
  Exam,
  ExamResult,
  FeePayment,
  Announcement,
  Enquiry,
  Event,
  Notification,
  FeeInvoice,
} from './useFirestoreData';
