// Student demo data for StudentInformation component

export interface Student {
  id: string;
  admissionNo: string;
  name: string;
  photo?: string;
  class: string;
  section: string;
  rollNo: string;
  dob: string;
  gender: string;
  bloodGroup: string;
  parentName: string;
  phone: string;
  email: string;
  address: string;
  feeStatus: 'paid' | 'partial' | 'pending';
  totalFee: number;
  paidFee: number;
  dueFee: number;
  attendance: number;
  presentDays: number;
  totalDays: number;
  classTeacher: string;
  classTeacherContact: string;
  transportRoute?: string;
  busNumber?: string;
  medicalInfo: {
    allergies: string[];
    conditions: string[];
    emergencyContact: string;
    emergencyPhone: string;
  };
}

export const demoStudents: Student[] = [
  // Class 1 Students
  {
    id: '1',
    admissionNo: 'ADM2024001',
    name: 'Aarav Patel',
    class: '1',
    section: 'A',
    rollNo: '01',
    dob: '2017-01-12',
    gender: 'Male',
    bloodGroup: 'O+',
    parentName: 'Ramesh Patel',
    phone: '+91 98765 43213',
    email: 'ramesh.patel@email.com',
    address: '45, Jayanagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 35000,
    paidFee: 35000,
    dueFee: 0,
    attendance: 98,
    presentDays: 59,
    totalDays: 60,
    classTeacher: 'Mrs. Kavita Reddy',
    classTeacherContact: '+91 98765 44444',
    transportRoute: 'Route 2 - Jayanagar',
    busNumber: 'BUS-02',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Ramesh Patel (Father)',
      emergencyPhone: '+91 98765 43213',
    },
  },
  {
    id: '2',
    admissionNo: 'ADM2024002',
    name: 'Ananya Desai',
    class: '1',
    section: 'A',
    rollNo: '02',
    dob: '2017-03-20',
    gender: 'Female',
    bloodGroup: 'A+',
    parentName: 'Sunil Desai',
    phone: '+91 98765 43214',
    email: 'sunil.desai@email.com',
    address: '78, Koramangala, Bangalore',
    feeStatus: 'paid',
    totalFee: 35000,
    paidFee: 35000,
    dueFee: 0,
    attendance: 96,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mrs. Kavita Reddy',
    classTeacherContact: '+91 98765 44444',
    medicalInfo: {
      allergies: ['Eggs'],
      conditions: [],
      emergencyContact: 'Sunil Desai (Father)',
      emergencyPhone: '+91 98765 43214',
    },
  },
  {
    id: '3',
    admissionNo: 'ADM2024003',
    name: 'Vivaan Iyer',
    class: '1',
    section: 'B',
    rollNo: '03',
    dob: '2017-05-08',
    gender: 'Male',
    bloodGroup: 'B+',
    parentName: 'Prakash Iyer',
    phone: '+91 98765 43215',
    email: 'prakash.iyer@email.com',
    address: '12, Indiranagar, Bangalore',
    feeStatus: 'partial',
    totalFee: 35000,
    paidFee: 20000,
    dueFee: 15000,
    attendance: 94,
    presentDays: 56,
    totalDays: 60,
    classTeacher: 'Mrs. Kavita Reddy',
    classTeacherContact: '+91 98765 44444',
    transportRoute: 'Route 4 - Indiranagar',
    busNumber: 'BUS-04',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Prakash Iyer (Father)',
      emergencyPhone: '+91 98765 43215',
    },
  },
  // Class 2 Students
  {
    id: '4',
    admissionNo: 'ADM2024004',
    name: 'Diya Kapoor',
    class: '2',
    section: 'A',
    rollNo: '05',
    dob: '2016-06-14',
    gender: 'Female',
    bloodGroup: 'O-',
    parentName: 'Anil Kapoor',
    phone: '+91 98765 43216',
    email: 'anil.kapoor@email.com',
    address: '89, Whitefield, Bangalore',
    feeStatus: 'paid',
    totalFee: 38000,
    paidFee: 38000,
    dueFee: 0,
    attendance: 97,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mr. Ravi Kumar',
    classTeacherContact: '+91 98765 55555',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Anil Kapoor (Father)',
      emergencyPhone: '+91 98765 43216',
    },
  },
  {
    id: '5',
    admissionNo: 'ADM2024005',
    name: 'Arjun Nair',
    class: '2',
    section: 'A',
    rollNo: '06',
    dob: '2016-09-25',
    gender: 'Male',
    bloodGroup: 'AB+',
    parentName: 'Vijay Nair',
    phone: '+91 98765 43217',
    email: 'vijay.nair@email.com',
    address: '34, HSR Layout, Bangalore',
    feeStatus: 'paid',
    totalFee: 38000,
    paidFee: 38000,
    dueFee: 0,
    attendance: 91,
    presentDays: 55,
    totalDays: 60,
    classTeacher: 'Mr. Ravi Kumar',
    classTeacherContact: '+91 98765 55555',
    transportRoute: 'Route 5 - HSR Layout',
    busNumber: 'BUS-05',
    medicalInfo: {
      allergies: ['Milk'],
      conditions: [],
      emergencyContact: 'Vijay Nair (Father)',
      emergencyPhone: '+91 98765 43217',
    },
  },
  {
    id: '6',
    admissionNo: 'ADM2024006',
    name: 'Sara Khan',
    class: '2',
    section: 'B',
    rollNo: '07',
    dob: '2016-11-30',
    gender: 'Female',
    bloodGroup: 'A-',
    parentName: 'Imran Khan',
    phone: '+91 98765 43218',
    email: 'imran.khan@email.com',
    address: '56, BTM Layout, Bangalore',
    feeStatus: 'pending',
    totalFee: 38000,
    paidFee: 5000,
    dueFee: 33000,
    attendance: 89,
    presentDays: 53,
    totalDays: 60,
    classTeacher: 'Mr. Ravi Kumar',
    classTeacherContact: '+91 98765 55555',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Imran Khan (Father)',
      emergencyPhone: '+91 98765 43218',
    },
  },
  // Class 3 Students
  {
    id: '7',
    admissionNo: 'ADM2024007',
    name: 'Rohan Gupta',
    class: '3',
    section: 'A',
    rollNo: '10',
    dob: '2015-04-18',
    gender: 'Male',
    bloodGroup: 'O+',
    parentName: 'Mahesh Gupta',
    phone: '+91 98765 43219',
    email: 'mahesh.gupta@email.com',
    address: '23, Electronic City, Bangalore',
    feeStatus: 'paid',
    totalFee: 42000,
    paidFee: 42000,
    dueFee: 0,
    attendance: 93,
    presentDays: 56,
    totalDays: 60,
    classTeacher: 'Mrs. Deepa Joshi',
    classTeacherContact: '+91 98765 66666',
    transportRoute: 'Route 6 - Electronic City',
    busNumber: 'BUS-06',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Mahesh Gupta (Father)',
      emergencyPhone: '+91 98765 43219',
    },
  },
  {
    id: '8',
    admissionNo: 'ADM2024008',
    name: 'Ishita Malhotra',
    class: '3',
    section: 'A',
    rollNo: '11',
    dob: '2015-07-22',
    gender: 'Female',
    bloodGroup: 'B+',
    parentName: 'Sanjay Malhotra',
    phone: '+91 98765 43220',
    email: 'sanjay.malhotra@email.com',
    address: '67, Marathahalli, Bangalore',
    feeStatus: 'partial',
    totalFee: 42000,
    paidFee: 25000,
    dueFee: 17000,
    attendance: 90,
    presentDays: 54,
    totalDays: 60,
    classTeacher: 'Mrs. Deepa Joshi',
    classTeacherContact: '+91 98765 66666',
    medicalInfo: {
      allergies: [],
      conditions: ['Diabetes'],
      emergencyContact: 'Sanjay Malhotra (Father)',
      emergencyPhone: '+91 98765 43220',
    },
  },
  {
    id: '9',
    admissionNo: 'ADM2024009',
    name: 'Kabir Mehta',
    class: '3',
    section: 'B',
    rollNo: '12',
    dob: '2015-10-05',
    gender: 'Male',
    bloodGroup: 'A+',
    parentName: 'Ranjan Mehta',
    phone: '+91 98765 43221',
    email: 'ranjan.mehta@email.com',
    address: '90, Bellandur, Bangalore',
    feeStatus: 'paid',
    totalFee: 42000,
    paidFee: 42000,
    dueFee: 0,
    attendance: 95,
    presentDays: 57,
    totalDays: 60,
    classTeacher: 'Mrs. Deepa Joshi',
    classTeacherContact: '+91 98765 66666',
    transportRoute: 'Route 7 - Bellandur',
    busNumber: 'BUS-07',
    medicalInfo: {
      allergies: ['Seafood'],
      conditions: [],
      emergencyContact: 'Ranjan Mehta (Father)',
      emergencyPhone: '+91 98765 43221',
    },
  },
  // Class 4 Students
  {
    id: '10',
    admissionNo: 'ADM2024010',
    name: 'Amit Singh',
    class: '4',
    section: 'A',
    rollNo: '08',
    dob: '2014-03-10',
    gender: 'Male',
    bloodGroup: 'B+',
    parentName: 'Vikas Singh',
    phone: '+91 98765 43212',
    email: 'vikas@email.com',
    address: '789, Residency Road, Bangalore',
    feeStatus: 'pending',
    totalFee: 50000,
    paidFee: 10000,
    dueFee: 40000,
    attendance: 92,
    presentDays: 55,
    totalDays: 60,
    classTeacher: 'Mrs. Priya Mehta',
    classTeacherContact: '+91 98765 33333',
    transportRoute: 'Route 1 - Residency Road',
    busNumber: 'BUS-01',
    medicalInfo: {
      allergies: ['Dust', 'Pollen'],
      conditions: [],
      emergencyContact: 'Vikas Singh (Father)',
      emergencyPhone: '+91 98765 43212',
    },
  },
  {
    id: '11',
    admissionNo: 'ADM2024011',
    name: 'Meera Reddy',
    class: '4',
    section: 'A',
    rollNo: '09',
    dob: '2014-02-14',
    gender: 'Female',
    bloodGroup: 'O+',
    parentName: 'Venkat Reddy',
    phone: '+91 98765 43222',
    email: 'venkat.reddy@email.com',
    address: '45, Sarjapur Road, Bangalore',
    feeStatus: 'paid',
    totalFee: 50000,
    paidFee: 50000,
    dueFee: 0,
    attendance: 96,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mrs. Priya Mehta',
    classTeacherContact: '+91 98765 33333',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Venkat Reddy (Father)',
      emergencyPhone: '+91 98765 43222',
    },
  },
  {
    id: '12',
    admissionNo: 'ADM2024012',
    name: 'Aditya Bose',
    class: '4',
    section: 'B',
    rollNo: '10',
    dob: '2014-05-28',
    gender: 'Male',
    bloodGroup: 'B-',
    parentName: 'Subhash Bose',
    phone: '+91 98765 43223',
    email: 'subhash.bose@email.com',
    address: '78, Bannerghatta Road, Bangalore',
    feeStatus: 'partial',
    totalFee: 50000,
    paidFee: 30000,
    dueFee: 20000,
    attendance: 87,
    presentDays: 52,
    totalDays: 60,
    classTeacher: 'Mrs. Priya Mehta',
    classTeacherContact: '+91 98765 33333',
    transportRoute: 'Route 8 - Bannerghatta',
    busNumber: 'BUS-08',
    medicalInfo: {
      allergies: ['Pollen', 'Grass'],
      conditions: [],
      emergencyContact: 'Subhash Bose (Father)',
      emergencyPhone: '+91 98765 43223',
    },
  },
  // Class 5 Students
  {
    id: '13',
    admissionNo: 'ADM2024013',
    name: 'Priya Sharma',
    class: '5',
    section: 'B',
    rollNo: '22',
    dob: '2013-08-22',
    gender: 'Female',
    bloodGroup: 'A+',
    parentName: 'Suresh Sharma',
    phone: '+91 98765 43211',
    email: 'suresh@email.com',
    address: '456, Brigade Road, Bangalore',
    feeStatus: 'partial',
    totalFee: 55000,
    paidFee: 30000,
    dueFee: 25000,
    attendance: 88,
    presentDays: 53,
    totalDays: 60,
    classTeacher: 'Mr. Amit Desai',
    classTeacherContact: '+91 98765 22222',
    medicalInfo: {
      allergies: [],
      conditions: ['Asthma'],
      emergencyContact: 'Suresh Sharma (Father)',
      emergencyPhone: '+91 98765 43211',
    },
  },
  {
    id: '14',
    admissionNo: 'ADM2024014',
    name: 'Nisha Varma',
    class: '5',
    section: 'A',
    rollNo: '20',
    dob: '2013-01-10',
    gender: 'Female',
    bloodGroup: 'AB+',
    parentName: 'Ashok Varma',
    phone: '+91 98765 43224',
    email: 'ashok.varma@email.com',
    address: '34, Yelahanka, Bangalore',
    feeStatus: 'paid',
    totalFee: 55000,
    paidFee: 55000,
    dueFee: 0,
    attendance: 94,
    presentDays: 56,
    totalDays: 60,
    classTeacher: 'Mr. Amit Desai',
    classTeacherContact: '+91 98765 22222',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Ashok Varma (Father)',
      emergencyPhone: '+91 98765 43224',
    },
  },
  {
    id: '15',
    admissionNo: 'ADM2024015',
    name: 'Karan Joshi',
    class: '5',
    section: 'A',
    rollNo: '21',
    dob: '2013-04-16',
    gender: 'Male',
    bloodGroup: 'O-',
    parentName: 'Dinesh Joshi',
    phone: '+91 98765 43225',
    email: 'dinesh.joshi@email.com',
    address: '56, Hebbal, Bangalore',
    feeStatus: 'paid',
    totalFee: 55000,
    paidFee: 55000,
    dueFee: 0,
    attendance: 91,
    presentDays: 55,
    totalDays: 60,
    classTeacher: 'Mr. Amit Desai',
    classTeacherContact: '+91 98765 22222',
    transportRoute: 'Route 9 - Hebbal',
    busNumber: 'BUS-09',
    medicalInfo: {
      allergies: ['Nuts'],
      conditions: [],
      emergencyContact: 'Dinesh Joshi (Father)',
      emergencyPhone: '+91 98765 43225',
    },
  },
  {
    id: '16',
    admissionNo: 'ADM2024016',
    name: 'Tanvi Saxena',
    class: '5',
    section: 'B',
    rollNo: '23',
    dob: '2013-09-12',
    gender: 'Female',
    bloodGroup: 'A+',
    parentName: 'Rakesh Saxena',
    phone: '+91 98765 43226',
    email: 'rakesh.saxena@email.com',
    address: '12, RT Nagar, Bangalore',
    feeStatus: 'pending',
    totalFee: 55000,
    paidFee: 15000,
    dueFee: 40000,
    attendance: 85,
    presentDays: 51,
    totalDays: 60,
    classTeacher: 'Mr. Amit Desai',
    classTeacherContact: '+91 98765 22222',
    medicalInfo: {
      allergies: [],
      conditions: ['Asthma'],
      emergencyContact: 'Rakesh Saxena (Father)',
      emergencyPhone: '+91 98765 43226',
    },
  },
  // Class 6 Students
  {
    id: '17',
    admissionNo: 'ADM2024017',
    name: 'Rahul Kumar',
    class: '6',
    section: 'A',
    rollNo: '15',
    dob: '2012-05-15',
    gender: 'Male',
    bloodGroup: 'O+',
    parentName: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh@email.com',
    address: '123, MG Road, Bangalore',
    feeStatus: 'paid',
    totalFee: 60000,
    paidFee: 60000,
    dueFee: 0,
    attendance: 95,
    presentDays: 57,
    totalDays: 60,
    classTeacher: 'Mrs. Sunita Verma',
    classTeacherContact: '+91 98765 11111',
    transportRoute: 'Route 3 - MG Road',
    busNumber: 'BUS-03',
    medicalInfo: {
      allergies: ['Peanuts'],
      conditions: [],
      emergencyContact: 'Rajesh Kumar (Father)',
      emergencyPhone: '+91 98765 43210',
    },
  },
  {
    id: '18',
    admissionNo: 'ADM2024018',
    name: 'Sneha Patel',
    class: '6',
    section: 'A',
    rollNo: '16',
    dob: '2012-03-08',
    gender: 'Female',
    bloodGroup: 'B+',
    parentName: 'Kishore Patel',
    phone: '+91 98765 43227',
    email: 'kishore.patel@email.com',
    address: '67, Malleshwaram, Bangalore',
    feeStatus: 'paid',
    totalFee: 60000,
    paidFee: 60000,
    dueFee: 0,
    attendance: 97,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mrs. Sunita Verma',
    classTeacherContact: '+91 98765 11111',
    transportRoute: 'Route 10 - Malleshwaram',
    busNumber: 'BUS-10',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Kishore Patel (Father)',
      emergencyPhone: '+91 98765 43227',
    },
  },
  {
    id: '19',
    admissionNo: 'ADM2024019',
    name: 'Dev Chatterjee',
    class: '6',
    section: 'B',
    rollNo: '17',
    dob: '2012-06-19',
    gender: 'Male',
    bloodGroup: 'O+',
    parentName: 'Soumya Chatterjee',
    phone: '+91 98765 43228',
    email: 'soumya.chatterjee@email.com',
    address: '89, Basavanagudi, Bangalore',
    feeStatus: 'partial',
    totalFee: 60000,
    paidFee: 40000,
    dueFee: 20000,
    attendance: 89,
    presentDays: 53,
    totalDays: 60,
    classTeacher: 'Mrs. Sunita Verma',
    classTeacherContact: '+91 98765 11111',
    medicalInfo: {
      allergies: ['Cats'],
      conditions: [],
      emergencyContact: 'Soumya Chatterjee (Father)',
      emergencyPhone: '+91 98765 43228',
    },
  },
  // Class 7 Students
  {
    id: '20',
    admissionNo: 'ADM2024020',
    name: 'Riya Bansal',
    class: '7',
    section: 'A',
    rollNo: '18',
    dob: '2011-02-25',
    gender: 'Female',
    bloodGroup: 'A-',
    parentName: 'Mohan Bansal',
    phone: '+91 98765 43229',
    email: 'mohan.bansal@email.com',
    address: '45, JP Nagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 65000,
    paidFee: 65000,
    dueFee: 0,
    attendance: 95,
    presentDays: 57,
    totalDays: 60,
    classTeacher: 'Mr. Suresh Naik',
    classTeacherContact: '+91 98765 77777',
    transportRoute: 'Route 1 - JP Nagar',
    busNumber: 'BUS-01',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Mohan Bansal (Father)',
      emergencyPhone: '+91 98765 43229',
    },
  },
  {
    id: '21',
    admissionNo: 'ADM2024021',
    name: 'Aryan Sinha',
    class: '7',
    section: 'A',
    rollNo: '19',
    dob: '2011-05-30',
    gender: 'Male',
    bloodGroup: 'B+',
    parentName: 'Arun Sinha',
    phone: '+91 98765 43230',
    email: 'arun.sinha@email.com',
    address: '78, Rajajinagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 65000,
    paidFee: 65000,
    dueFee: 0,
    attendance: 92,
    presentDays: 55,
    totalDays: 60,
    classTeacher: 'Mr. Suresh Naik',
    classTeacherContact: '+91 98765 77777',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Arun Sinha (Father)',
      emergencyPhone: '+91 98765 43230',
    },
  },
  {
    id: '22',
    admissionNo: 'ADM2024022',
    name: 'Navya Rao',
    class: '7',
    section: 'B',
    rollNo: '20',
    dob: '2011-08-14',
    gender: 'Female',
    bloodGroup: 'AB-',
    parentName: 'Prasad Rao',
    phone: '+91 98765 43231',
    email: 'prasad.rao@email.com',
    address: '23, Vijayanagar, Bangalore',
    feeStatus: 'partial',
    totalFee: 65000,
    paidFee: 35000,
    dueFee: 30000,
    attendance: 88,
    presentDays: 53,
    totalDays: 60,
    classTeacher: 'Mr. Suresh Naik',
    classTeacherContact: '+91 98765 77777',
    transportRoute: 'Route 2 - Vijayanagar',
    busNumber: 'BUS-02',
    medicalInfo: {
      allergies: ['Penicillin'],
      conditions: [],
      emergencyContact: 'Prasad Rao (Father)',
      emergencyPhone: '+91 98765 43231',
    },
  },
  // Class 8 Students
  {
    id: '23',
    admissionNo: 'ADM2024023',
    name: 'Siddharth Menon',
    class: '8',
    section: 'A',
    rollNo: '21',
    dob: '2010-03-17',
    gender: 'Male',
    bloodGroup: 'O+',
    parentName: 'Gopal Menon',
    phone: '+91 98765 43232',
    email: 'gopal.menon@email.com',
    address: '56, Nagarbhavi, Bangalore',
    feeStatus: 'paid',
    totalFee: 70000,
    paidFee: 70000,
    dueFee: 0,
    attendance: 94,
    presentDays: 56,
    totalDays: 60,
    classTeacher: 'Mrs. Lakshmi Iyer',
    classTeacherContact: '+91 98765 88888',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Gopal Menon (Father)',
      emergencyPhone: '+91 98765 43232',
    },
  },
  {
    id: '24',
    admissionNo: 'ADM2024024',
    name: 'Aisha Ahmed',
    class: '8',
    section: 'A',
    rollNo: '22',
    dob: '2010-07-22',
    gender: 'Female',
    bloodGroup: 'A+',
    parentName: 'Salman Ahmed',
    phone: '+91 98765 43233',
    email: 'salman.ahmed@email.com',
    address: '12, Frazer Town, Bangalore',
    feeStatus: 'paid',
    totalFee: 70000,
    paidFee: 70000,
    dueFee: 0,
    attendance: 96,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mrs. Lakshmi Iyer',
    classTeacherContact: '+91 98765 88888',
    transportRoute: 'Route 3 - Frazer Town',
    busNumber: 'BUS-03',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Salman Ahmed (Father)',
      emergencyPhone: '+91 98765 43233',
    },
  },
  {
    id: '25',
    admissionNo: 'ADM2024025',
    name: 'Varun Pillai',
    class: '8',
    section: 'B',
    rollNo: '23',
    dob: '2010-10-11',
    gender: 'Male',
    bloodGroup: 'B-',
    parentName: 'Ramesh Pillai',
    phone: '+91 98765 43234',
    email: 'ramesh.pillai@email.com',
    address: '34, Kammanahalli, Bangalore',
    feeStatus: 'pending',
    totalFee: 70000,
    paidFee: 20000,
    dueFee: 50000,
    attendance: 82,
    presentDays: 49,
    totalDays: 60,
    classTeacher: 'Mrs. Lakshmi Iyer',
    classTeacherContact: '+91 98765 88888',
    medicalInfo: {
      allergies: [],
      conditions: ['Heart condition'],
      emergencyContact: 'Ramesh Pillai (Father)',
      emergencyPhone: '+91 98765 43234',
    },
  },
  // Class 9 Students
  {
    id: '26',
    admissionNo: 'ADM2024026',
    name: 'Aditi Kulkarni',
    class: '9',
    section: 'A',
    rollNo: '24',
    dob: '2009-01-05',
    gender: 'Female',
    bloodGroup: 'O+',
    parentName: 'Pradeep Kulkarni',
    phone: '+91 98765 43235',
    email: 'pradeep.kulkarni@email.com',
    address: '67, Sadashivanagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 75000,
    paidFee: 75000,
    dueFee: 0,
    attendance: 93,
    presentDays: 56,
    totalDays: 60,
    classTeacher: 'Mr. Ganesh Rao',
    classTeacherContact: '+91 98765 99999',
    transportRoute: 'Route 4 - Sadashivanagar',
    busNumber: 'BUS-04',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Pradeep Kulkarni (Father)',
      emergencyPhone: '+91 98765 43235',
    },
  },
  {
    id: '27',
    admissionNo: 'ADM2024027',
    name: 'Yash Malhotra',
    class: '9',
    section: 'A',
    rollNo: '25',
    dob: '2009-04-20',
    gender: 'Male',
    bloodGroup: 'AB+',
    parentName: 'Sandeep Malhotra',
    phone: '+91 98765 43236',
    email: 'sandeep.malhotra@email.com',
    address: '89, CV Raman Nagar, Bangalore',
    feeStatus: 'partial',
    totalFee: 75000,
    paidFee: 50000,
    dueFee: 25000,
    attendance: 90,
    presentDays: 54,
    totalDays: 60,
    classTeacher: 'Mr. Ganesh Rao',
    classTeacherContact: '+91 98765 99999',
    medicalInfo: {
      allergies: ['Shellfish'],
      conditions: [],
      emergencyContact: 'Sandeep Malhotra (Father)',
      emergencyPhone: '+91 98765 43236',
    },
  },
  {
    id: '28',
    admissionNo: 'ADM2024028',
    name: 'Pooja Shetty',
    class: '9',
    section: 'B',
    rollNo: '26',
    dob: '2009-09-15',
    gender: 'Female',
    bloodGroup: 'A-',
    parentName: 'Krishna Shetty',
    phone: '+91 98765 43237',
    email: 'krishna.shetty@email.com',
    address: '45, RT Nagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 75000,
    paidFee: 75000,
    dueFee: 0,
    attendance: 97,
    presentDays: 58,
    totalDays: 60,
    classTeacher: 'Mr. Ganesh Rao',
    classTeacherContact: '+91 98765 99999',
    transportRoute: 'Route 5 - RT Nagar',
    busNumber: 'BUS-05',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Krishna Shetty (Father)',
      emergencyPhone: '+91 98765 43237',
    },
  },
  // Class 10 Students
  {
    id: '29',
    admissionNo: 'ADM2024029',
    name: 'Akash Jain',
    class: '10',
    section: 'A',
    rollNo: '27',
    dob: '2008-02-28',
    gender: 'Male',
    bloodGroup: 'B+',
    parentName: 'Mahendra Jain',
    phone: '+91 98765 43238',
    email: 'mahendra.jain@email.com',
    address: '23, Shivajinagar, Bangalore',
    feeStatus: 'paid',
    totalFee: 80000,
    paidFee: 80000,
    dueFee: 0,
    attendance: 98,
    presentDays: 59,
    totalDays: 60,
    classTeacher: 'Mrs. Anita Sharma',
    classTeacherContact: '+91 98765 00000',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Mahendra Jain (Father)',
      emergencyPhone: '+91 98765 43238',
    },
  },
  {
    id: '30',
    admissionNo: 'ADM2024030',
    name: 'Neha Agarwal',
    class: '10',
    section: 'A',
    rollNo: '28',
    dob: '2008-05-12',
    gender: 'Female',
    bloodGroup: 'O-',
    parentName: 'Vinod Agarwal',
    phone: '+91 98765 43239',
    email: 'vinod.agarwal@email.com',
    address: '56, Palace Road, Bangalore',
    feeStatus: 'paid',
    totalFee: 80000,
    paidFee: 80000,
    dueFee: 0,
    attendance: 95,
    presentDays: 57,
    totalDays: 60,
    classTeacher: 'Mrs. Anita Sharma',
    classTeacherContact: '+91 98765 00000',
    transportRoute: 'Route 6 - Palace Road',
    busNumber: 'BUS-06',
    medicalInfo: {
      allergies: [],
      conditions: [],
      emergencyContact: 'Vinod Agarwal (Father)',
      emergencyPhone: '+91 98765 43239',
    },
  },
  {
    id: '31',
    admissionNo: 'ADM2024031',
    name: 'Rohit Singh',
    class: '10',
    section: 'B',
    rollNo: '29',
    dob: '2008-08-07',
    gender: 'Male',
    bloodGroup: 'A+',
    parentName: 'Suresh Singh',
    phone: '+91 98765 43240',
    email: 'suresh.singh@email.com',
    address: '12, Cunningham Road, Bangalore',
    feeStatus: 'partial',
    totalFee: 80000,
    paidFee: 60000,
    dueFee: 20000,
    attendance: 91,
    presentDays: 55,
    totalDays: 60,
    classTeacher: 'Mrs. Anita Sharma',
    classTeacherContact: '+91 98765 00000',
    medicalInfo: {
      allergies: ['Dust mites'],
      conditions: [],
      emergencyContact: 'Suresh Singh (Father)',
      emergencyPhone: '+91 98765 43240',
    },
  },
];
